[tool.poetry]
name = "gliff"
version = "0.1.0"
description = "gliff.ai SDK - a Python SDL for developing AI-in-the-loop trusted services for the gliff.ai platform"
authors = ["Chas Nelson <chas@gliff.ai>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^4.0.1"
black = "^21.10b0"

[tool.poetry.scripts]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
